version: 1.0
provider:
  name: openfaas
  gateway: http://10.0.1.2:8080

functions:
  url-to-hash:
    lang: golang-http
    handler: ./url-to-hash
    image: url-to-hash:latest
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT: http://10.0.1.2:8000
      DYNAMODB_TABLE: url_mappings
      COUNTER_TABLE: url_counter
      BASE_URL: http://10.0.1.2:8080
      QRCODE_FUNCTION: http://10.0.1.2:8080/function/qrcode-go
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "5"

  redirect:
    lang: golang-http
    handler: ./redirect
    image: redirect:latest
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_ENDPOINT: http://10.0.1.2:8000
      DYNAMODB_TABLE: url_mappings
      COUNTER_TABLE: url_counter
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "10"
